package com.atsuishio.superbwarfare.init

import com.atsuishio.superbwarfare.client.renderer.entity.*
import com.atsuishio.superbwarfare.client.renderer.projectile.*
import net.fabricmc.fabric.api.client.rendering.v1.EntityRendererRegistry

/** Клиентская сторона: вызывать из ClientModInitializer. */
object ModEntityRenderers {
    fun init() {
        EntityRendererRegistry.register(ModEntities.MORTAR.get(), ::MortarRenderer)
        EntityRendererRegistry.register(ModEntities.SENPAI.get(), ::SenpaiRenderer)
        EntityRendererRegistry.register(ModEntities.CLAYMORE.get(), ::ClaymoreRenderer)
        EntityRendererRegistry.register(ModEntities.C4.get(), ::C4Renderer)
        EntityRendererRegistry.register(ModEntities.TASER_BULLET.get(), ::BasicProjectileRenderer)
        EntityRendererRegistry.register(ModEntities.GUN_GRENADE.get(), ::BasicProjectileRenderer)
        EntityRendererRegistry.register(ModEntities.TARGET.get(), ::TargetRenderer)
        EntityRendererRegistry.register(ModEntities.DPS_GENERATOR.get(), ::DPSGeneratorRenderer)
        EntityRendererRegistry.register(ModEntities.RPG_ROCKET_TBG.get(), ::BasicProjectileRenderer)
        EntityRendererRegistry.register(ModEntities.RPG_ROCKET_STANDARD.get(), ::BasicProjectileRenderer)
        EntityRendererRegistry.register(ModEntities.SMALL_ROCKET.get(), ::BasicProjectileRenderer)
        EntityRendererRegistry.register(ModEntities.MEDIUM_ROCKET.get(), ::BasicProjectileRenderer)
        EntityRendererRegistry.register(ModEntities.MORTAR_SHELL.get(), ::BasicProjectileRenderer)
        EntityRendererRegistry.register(ModEntities.CANNON_SHELL.get(), ::BasicProjectileRenderer)
        EntityRendererRegistry.register(ModEntities.PROJECTILE.get(), ::ProjectileEntityRenderer)
        EntityRendererRegistry.register(ModEntities.MK_42.get(), ::Mk42Renderer)
        EntityRendererRegistry.register(ModEntities.DRONE.get(), ::DroneRenderer)
        EntityRendererRegistry.register(ModEntities.HAND_GRENADE.get(), ::BasicProjectileRenderer)
        EntityRendererRegistry.register(ModEntities.RGO_GRENADE.get(), ::BasicProjectileRenderer)
        EntityRendererRegistry.register(ModEntities.M18_SMOKE_GRENADE.get(), ::BasicProjectileRenderer)
        EntityRendererRegistry.register(ModEntities.MLE_1934.get(), ::Mle1934Renderer)
        EntityRendererRegistry.register(ModEntities.JAVELIN_MISSILE.get(), ::BasicProjectileRenderer)
        EntityRendererRegistry.register(ModEntities.ANNIHILATOR.get(), ::AnnihilatorRenderer)
        EntityRendererRegistry.register(ModEntities.SPEEDBOAT.get(), ::SpeedBoatRenderer)
        EntityRendererRegistry.register(ModEntities.TINY_SPEEDBOAT.get(), ::TinySpeedboatRenderer)
        EntityRendererRegistry.register(ModEntities.WHEEL_CHAIR.get(), ::WheelChairRenderer)
        EntityRendererRegistry.register(ModEntities.AH_6.get(), ::Ah6Renderer)
        EntityRendererRegistry.register(ModEntities.FLARE_DECOY.get(), ::FlareDecoyEntityRenderer)
        EntityRendererRegistry.register(ModEntities.CATAPULT_SHUTTLE.get(), ::CatapultShuttleRenderer)
        EntityRendererRegistry.register(
            ModEntities.WHITE_PHOSPHORUS_PROJECTILE.get(),
            ::WhitePhosphorusProjectileEntityRenderer
        )
        EntityRendererRegistry.register(ModEntities.PRISMATIC_BOLT.get(), ::PrismaticBoltEntityRenderer)
        EntityRendererRegistry.register(ModEntities.SMOKE_DECOY.get(), ::SmokeDecoyEntityRenderer)
        EntityRendererRegistry.register(ModEntities.LAV_150.get(), ::Lav150Renderer)
        EntityRendererRegistry.register(ModEntities.SMALL_CANNON_SHELL.get(), ::SmallCannonShellEntityRenderer)
        EntityRendererRegistry.register(ModEntities.TOM_6.get(), ::Tom6Renderer)
        EntityRendererRegistry.register(ModEntities.MELON_BOMB.get(), ::MelonBombEntityRenderer)
        EntityRendererRegistry.register(ModEntities.BMP_2.get(), ::Bmp2Renderer)
        EntityRendererRegistry.register(ModEntities.WIRE_GUIDE_MISSILE.get(), ::BasicProjectileRenderer)
        EntityRendererRegistry.register(ModEntities.LASER_TOWER.get(), ::LaserTowerRenderer)
        EntityRendererRegistry.register(ModEntities.YX_100.get(), ::Yx100Renderer)
        EntityRendererRegistry.register(ModEntities.PRISM_TANK.get(), ::PrismTankRenderer)
        EntityRendererRegistry.register(ModEntities.SWARM_DRONE.get(), ::BasicProjectileRenderer)
        EntityRendererRegistry.register(ModEntities.HPJ_11.get(), ::Hpj11Renderer)
        EntityRendererRegistry.register(ModEntities.A_10A.get(), ::A10Renderer)
        EntityRendererRegistry.register(ModEntities.AIR_SHEEP.get(), ::AirSheepRenderer)
        EntityRendererRegistry.register(ModEntities.HAPPIEST_GHAST.get(), ::HappiestGhastRenderer)
        EntityRendererRegistry.register(ModEntities.KIROV.get(), ::KirovRenderer)
        EntityRendererRegistry.register(ModEntities.MK_82.get(), ::BasicProjectileRenderer)
        EntityRendererRegistry.register(ModEntities.MK_84.get(), ::BasicProjectileRenderer)
        EntityRendererRegistry.register(ModEntities.BOR_57.get(), ::BasicProjectileRenderer)
        EntityRendererRegistry.register(ModEntities.SC_50.get(), ::BasicProjectileRenderer)
        EntityRendererRegistry.register(ModEntities.SC_250.get(), ::BasicProjectileRenderer)
        EntityRendererRegistry.register(ModEntities.AGM_65.get(), ::BasicProjectileRenderer)
        EntityRendererRegistry.register(ModEntities.BLU_43.get(), ::Blu43Renderer)
        EntityRendererRegistry.register(ModEntities.TM_62.get(), ::Tm62Renderer)
        EntityRendererRegistry.register(ModEntities.PTKM_1R.get(), ::Ptkm1rRenderer)
        EntityRendererRegistry.register(ModEntities.PTKM_PROJECTILE.get(), ::BasicProjectileRenderer)
        EntityRendererRegistry.register(ModEntities.TYPE_63.get(), ::Type63Renderer)
        EntityRendererRegistry.register(ModEntities.MEDICAL_KIT.get(), ::MedicalKitEntityRenderer)
        EntityRendererRegistry.register(ModEntities.BL_132.get(), ::Bl132Renderer)
        EntityRendererRegistry.register(ModEntities.GRAPESHOT.get(), ::GrapeshotRenderer)
        EntityRendererRegistry.register(ModEntities.SUPER_STAR_PROJECTILE.get(), ::SuperStarProjectileRenderer)
        EntityRendererRegistry.register(ModEntities.VEHICLE_ASSEMBLING_TABLE.get(), ::VehicleAssemblingTableVehicleRenderer)
        EntityRendererRegistry.register(ModEntities.WAVEFORCE_TOWER.get(), ::WaveforceTowerRenderer)
        EntityRendererRegistry.register(ModEntities.IGLA_MISSILE.get(), ::BasicProjectileRenderer)
        EntityRendererRegistry.register(ModEntities.RU_9M336_MISSILE.get(), ::BasicProjectileRenderer)
        EntityRendererRegistry.register(ModEntities.RU_9M100_MISSILE.get(), ::BasicProjectileRenderer)
        EntityRendererRegistry.register(ModEntities.RU_3M14_MISSILE.get(), ::BasicProjectileRenderer)
        EntityRendererRegistry.register(ModEntities.TRUCK.get(), ::TruckRenderer)
        EntityRendererRegistry.register(ModEntities.SODAYO_PICK_UP.get(), ::SodayoPickUpRenderer)
        EntityRendererRegistry.register(ModEntities.SODAYO_PICK_UP_HMG.get(), ::SodayoPickUpRenderer)
        EntityRendererRegistry.register(ModEntities.SODAYO_PICK_UP_ROCKET.get(), ::SodayoPickUpRenderer)
        EntityRendererRegistry.register(ModEntities.SODAYO_PICK_UP_TOW.get(), ::SodayoPickUpRenderer)
        EntityRendererRegistry.register(ModEntities.TOW.get(), ::TowRenderer)
        EntityRendererRegistry.register(ModEntities.STEEL_COIL.get(), ::SteelCoilRenderer)
        EntityRendererRegistry.register(ModEntities.MI_28.get(), ::Mi28Renderer)
        EntityRendererRegistry.register(ModEntities.KH_39.get(), ::BasicProjectileRenderer)
        EntityRendererRegistry.register(ModEntities.PLZ_05.get(), ::Plz05Renderer)
        EntityRendererRegistry.register(ModEntities.FH_77BW.get(), ::Fh88bwRenderer)
        EntityRendererRegistry.register(ModEntities.LAV_AD.get(), ::LavAdRenderer)
        EntityRendererRegistry.register(ModEntities.KV_16.get(), ::Kv16Renderer)
        EntityRendererRegistry.register(ModEntities.JU_87.get(), ::Ju87Renderer)
        EntityRendererRegistry.register(ModEntities.T_90A.get(), ::T90aRenderer)
        EntityRendererRegistry.register(ModEntities.M_1A_2.get(), ::M1A2Renderer)
        EntityRendererRegistry.register(ModEntities.BRADLEY.get(), ::BradleyRenderer)
        EntityRendererRegistry.register(ModEntities.TURRET_WRECK.get(), ::TurretWreckRenderer)
        EntityRendererRegistry.register(ModEntities.LAV_25.get(), ::Lav25Renderer)
        EntityRendererRegistry.register(ModEntities.ZTZ_99A.get(), ::Ztz99aRenderer)
        EntityRendererRegistry.register(ModEntities.EDD.get(), ::EDDRenderer)
        EntityRendererRegistry.register(ModEntities.AC_130H.get(), ::Ac130hRenderer)
        EntityRendererRegistry.register(ModEntities.J_16.get(), ::J16Renderer)
        EntityRendererRegistry.register(ModEntities.FIM_92_MISSILE.get(), ::BasicProjectileRenderer)
    }
}
